### ISSUE TITLE
Chatbot: Permissions needed

### ISSUE THREAD

**Issue by odyss3y** [SilenusTA/StreamRoller#38]
permission levels for both actions (casual dialog and direct questions) as well as various user levels (regular/sub/vip/mod)

**Comment by SilenusTA** [comment]
Good idea, I can also look at adding in donation permissions as we have all that data available :D. I should also add an option to have it take Discord/twitter messages etc.
That sounds fun, a Twitter checkbox so that it auto-replies to anyone on Twitter :D Maybe I should start a new Twitter account just for that 🗡️

**Comment by SilenusTA** [comment]
Added an ignore list but currently global. Will see if people want an ignore list just for the direct questions, English translation etc as time goes on. Just trying to avoid having 10 pages of checkboxes at the moment :D
